"""Obsidian vault I/O — parse touch notes (any register), resolve person notes, surgical frontmatter writeback."""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path
from typing import Optional

import yaml

from config import CONVERSATIONS_DIR, PEOPLE_DIR, TOUCH_NOTE_GLOB


FRONTMATTER_RE = re.compile(r"^---\n(.*?)\n---\n(.*)$", re.DOTALL)
WIKILINK_RE = re.compile(r"\[\[([^\]]+)\]\]")

# Match `## Email`, `## Email — v3`, `## Email — v3.1 (insight-led)`, etc.
EMAIL_SECTION_RE = re.compile(r"^##\s+Email\b[^\n]*\n", re.MULTILINE)
LINKEDIN_SECTION_RE = re.compile(r"^##\s+LinkedIn\s+DM\b[^\n]*\n", re.MULTILINE)
LINKEDIN_INVITE_SECTION_RE = re.compile(r"^##\s+LinkedIn\s+(?:Invite|Connection)\b[^\n]*\n", re.MULTILINE)
# Pillar C Week 5 (ADR-0018) — Twitter DM section heading. Touch notes
# carrying ``channel: twitter`` use a ``## Twitter DM`` (or ``## Twitter``)
# header with a fenced code block body. Twitter has one outreach action,
# so the regex doesn't discriminate by action — every Twitter touch is a
# DM (per ADR-0018 D61's deferral of the ``twitter_action:`` field).
TWITTER_DM_SECTION_RE = re.compile(r"^##\s+Twitter(?:\s+DM)?\b[^\n]*\n", re.MULTILINE)
# Pillar C Week 6 (ADR-0019) — Calendar booking section heading. Touch
# notes carrying ``channel: calendar`` use a ``## Calendar`` (or
# ``## Calendar Booking``) header with a fenced code block body. The
# fence body is the cover message the operator sends with the booking
# link; the link itself is generated by the dispatcher per ADR-0019 D65
# (URL-fragment intent-id marker — distinct from the zero-width-Unicode
# marker shape used for in-message channels because Cal.com URLs are
# structured artifacts with their own query-param semantics).
CALENDAR_SECTION_RE = re.compile(r"^##\s+Calendar(?:\s+Booking)?\b[^\n]*\n", re.MULTILINE)

SUBJECT_RE = re.compile(r"\*\*Subject:\*\*\s*`([^`]+)`")
FENCE_RE = re.compile(r"^```(?:\w*\n)?(.*?)^```", re.MULTILINE | re.DOTALL)


@dataclass
class PersonInfo:
    name: str
    note_path: Path
    email: Optional[str]
    linkedin: Optional[str]
    status: Optional[str]
    email_verified_status: Optional[str] = None  # safe | catch_all | invalid | disposable | spamtrap
    email_risk: Optional[str] = None  # e.g. "catch_all"
    email_skip_reason: Optional[str] = None  # set when prior verification refused the guess
    research_tier: Optional[str] = None  # S | A | B (per Outreach Tier Playbook)
    twitter_handle: Optional[str] = None  # Pillar C Week 5 (ADR-0018 D60) — channel surface for the Twitter DM dispatcher
    calendar_booking_url_base: Optional[str] = None  # Pillar C Week 6 (ADR-0019 D65) — optional per-Person Cal.com link override; absent → dispatcher uses operator-default


# Reoon verification statuses that mean: do NOT send. Source of truth:
# memory/reoon-email-verifier-validated-2026-05-12.md
EMAIL_HARD_SKIP_STATUSES = {"invalid", "disposable", "spamtrap"}


@dataclass
class TouchDraft:
    note_path: Path
    frontmatter: dict
    body: str
    person_name: str
    person: Optional[PersonInfo]
    channel_declared: str  # from frontmatter
    has_email_block: bool
    has_linkedin_block: bool
    email_subject: Optional[str]
    email_body: Optional[str]
    linkedin_dm: Optional[str]
    # Pillar C Week 5 (ADR-0018) — Twitter DM block parse state.
    has_twitter_block: bool = False
    twitter_dm: Optional[str] = None
    # Pillar C Week 6 (ADR-0019) — Calendar booking block parse state.
    # ``calendar_cover_message`` is the operator-authored cover prose
    # that surrounds the dispatcher-generated booking URL; the URL
    # itself is NOT in the touch body at parse time (the dispatcher
    # synthesizes ``<base>?intent_id=cb_<ULID>`` and writes it back per
    # ADR-0019 D65 — the touch body's role is the human-facing context).
    has_calendar_block: bool = False
    calendar_cover_message: Optional[str] = None
    issues: list[str] = field(default_factory=list)


def split_frontmatter(text: str) -> tuple[dict, str]:
    m = FRONTMATTER_RE.match(text)
    if not m:
        return {}, text
    raw_fm, body = m.group(1), m.group(2)
    try:
        fm = yaml.safe_load(raw_fm) or {}
    except yaml.YAMLError:
        fm = {}
    return fm, body


def _extract_wikilink_name(value) -> Optional[str]:
    if not value:
        return None
    if isinstance(value, str):
        m = WIKILINK_RE.search(value)
        if m:
            return m.group(1).strip()
        return value.strip() or None
    return None


def _strip_email_comment(raw: str) -> Optional[str]:
    """Person notes use: `mohammad@open.cx  # guess-unverified (first) | alts: ...`"""
    if not raw:
        return None
    # Drop everything after first `#`
    cleaned = raw.split("#", 1)[0].strip()
    # If contains pipe (no comment delimiter), take first alt
    if "|" in cleaned:
        cleaned = cleaned.split("|", 1)[0].strip()
    return cleaned or None


def _read_raw_frontmatter_value(note_path: Path, key: str) -> Optional[str]:
    """Read a frontmatter field as the raw string (preserves trailing `# comments`).

    PyYAML drops `#` comments, but we need the un-cleaned value to parse email aliases.
    """
    try:
        text = note_path.read_text()
    except OSError:
        return None
    m = FRONTMATTER_RE.match(text)
    if not m:
        return None
    fm_text = m.group(1)
    for line in fm_text.splitlines():
        if line.startswith(f"{key}:"):
            return line[len(key) + 1 :].strip()
    return None


def find_person_note(name: str) -> Optional[Path]:
    """Search 10 People/**/Name.md across all status subdirs."""
    # Obsidian wikilink may include emoji in path; we match by filename stem == name
    matches = list(PEOPLE_DIR.rglob(f"{name}.md"))
    if matches:
        return matches[0]
    # Try case-insensitive fallback
    target = f"{name.lower()}.md"
    for p in PEOPLE_DIR.rglob("*.md"):
        if p.name.lower() == target:
            return p
    return None


def load_person(name: str) -> Optional[PersonInfo]:
    note_path = find_person_note(name)
    if not note_path:
        return None
    fm, _body = split_frontmatter(note_path.read_text())
    raw_email = _read_raw_frontmatter_value(note_path, "email")
    email = _strip_email_comment(raw_email) if raw_email else None
    email_verified_status = (fm.get("email_verified_status") or None)
    if isinstance(email_verified_status, str):
        email_verified_status = email_verified_status.lower()
    skip_reason = fm.get("email_skip_reason") or None
    # Hard-skip gate: refuse to expose a recipient address that prior verification
    # flagged as unsendable. The skip_no_email bucket downstream will surface it.
    if email and (
        (email_verified_status in EMAIL_HARD_SKIP_STATUSES) or skip_reason
    ):
        email = None
    twitter_handle_raw = fm.get("twitter_handle") or fm.get("twitter") or None
    twitter_handle: Optional[str] = None
    if isinstance(twitter_handle_raw, str):
        stripped = twitter_handle_raw.strip().lstrip("@")
        twitter_handle = stripped or None
    # Pillar C Week 6 (ADR-0019 D65) — optional per-Person Cal.com base
    # URL override. Operators with multiple booking link types (intro
    # call vs deep-dive vs partnership) stamp a per-Person URL on the
    # Person note; absent → the dispatcher's operator-default applies.
    cal_base_raw = fm.get("calendar_booking_url_base") or None
    calendar_base: Optional[str] = None
    if isinstance(cal_base_raw, str):
        calendar_base = cal_base_raw.strip() or None
    return PersonInfo(
        name=name,
        note_path=note_path,
        email=email if email and "@" in email else None,
        linkedin=fm.get("linkedin") or None,
        status=fm.get("status") or None,
        email_verified_status=email_verified_status,
        email_risk=fm.get("email_risk") or None,
        email_skip_reason=skip_reason,
        research_tier=fm.get("research_tier") or None,
        twitter_handle=twitter_handle,
        calendar_booking_url_base=calendar_base,
    )


def _find_section_block(body: str, section_re: re.Pattern) -> Optional[str]:
    """Find the section header, return the substring from header to next h2 or EOF."""
    m = section_re.search(body)
    if not m:
        return None
    start = m.end()
    # Stop at next ## heading
    next_h2 = re.search(r"^##\s", body[start:], re.MULTILINE)
    end = start + next_h2.start() if next_h2 else len(body)
    return body[start:end]


def _extract_first_fence(block: str) -> Optional[str]:
    m = FENCE_RE.search(block)
    if not m:
        return None
    return m.group(1).rstrip("\n")


def parse_touch_note(note_path: Path) -> TouchDraft:
    text = note_path.read_text()
    fm, body = split_frontmatter(text)

    person_name = _extract_wikilink_name(fm.get("person")) or ""
    person = load_person(person_name) if person_name else None

    issues: list[str] = []
    if not person_name:
        issues.append("No `person:` frontmatter or unparseable wikilink")
    elif not person:
        issues.append(f"Person note not found for [[{person_name}]]")

    email_block = _find_section_block(body, EMAIL_SECTION_RE)
    linkedin_block = _find_section_block(body, LINKEDIN_SECTION_RE)
    twitter_block = _find_section_block(body, TWITTER_DM_SECTION_RE)
    calendar_block = _find_section_block(body, CALENDAR_SECTION_RE)

    email_subject = email_body = None
    if email_block:
        sm = SUBJECT_RE.search(email_block)
        email_subject = sm.group(1).strip() if sm else None
        email_body = _extract_first_fence(email_block)
        if not email_subject:
            issues.append("Email block found but no **Subject:** `...` line")
        if not email_body:
            issues.append("Email block found but no fenced code block body")

    linkedin_dm = _extract_first_fence(linkedin_block) if linkedin_block else None
    if linkedin_block and not linkedin_dm:
        issues.append("LinkedIn DM section found but no fenced code block")

    twitter_dm = _extract_first_fence(twitter_block) if twitter_block else None
    if twitter_block and not twitter_dm:
        issues.append("Twitter DM section found but no fenced code block")

    calendar_cover_message = (
        _extract_first_fence(calendar_block) if calendar_block else None
    )
    if calendar_block and not calendar_cover_message:
        issues.append("Calendar section found but no fenced code block")

    return TouchDraft(
        note_path=note_path,
        frontmatter=fm,
        body=body,
        person_name=person_name,
        person=person,
        channel_declared=str(fm.get("channel") or ""),
        has_email_block=bool(email_block and email_subject and email_body),
        has_linkedin_block=bool(linkedin_block and linkedin_dm),
        email_subject=email_subject,
        email_body=email_body,
        linkedin_dm=linkedin_dm,
        has_twitter_block=bool(twitter_block and twitter_dm),
        twitter_dm=twitter_dm,
        has_calendar_block=bool(calendar_block and calendar_cover_message),
        calendar_cover_message=calendar_cover_message,
        issues=issues,
    )


def find_unsent_touches() -> list[TouchDraft]:
    """Back-compat alias for find_pending_touches() — kept so external callers don't break."""
    return find_pending_touches()


# Terminal LI states = no further outbound action ever
LI_TERMINAL_STATES = {"dm_sent", "invite_failed", "declined", "follow_only"}
# Invite-awaiting states = invite sent, waiting on acceptance (handled by --li-check, not default send)
LI_AWAITING_STATES = {"invited"}


def _email_pending(draft: TouchDraft) -> bool:
    """True if the touch has an email block + recipient and `sent: false`."""
    return (
        draft.has_email_block
        and bool(draft.person and draft.person.email)
        and draft.frontmatter.get("sent") is not True
    )


def _linkedin_invite_pending(draft: TouchDraft) -> bool:
    """True if a fresh LinkedIn connection request still needs to be sent."""
    if not draft.has_linkedin_block:
        return False
    if not (draft.person and draft.person.linkedin):
        return False
    state = draft.frontmatter.get("linkedin_state")
    if state in LI_TERMINAL_STATES or state in LI_AWAITING_STATES:
        return False
    return True


def _linkedin_dm_pending(draft: TouchDraft) -> bool:
    """True if the invite has been accepted and the DM still needs to be sent."""
    if not draft.has_linkedin_block:
        return False
    return draft.frontmatter.get("linkedin_state") == "connected"


# Back-compat alias used by send_queued.py
_linkedin_pending = _linkedin_invite_pending


def find_pending_touches() -> list[TouchDraft]:
    """Scan vault for cold-touch notes with at least one channel still actionable.

    Returns touches where either:
      - email is sendable (has email block + recipient + sent != true), OR
      - LinkedIn is invitable (has LinkedIn DM block + URL + linkedin_state not terminal)
    """
    drafts = []
    for note_path in sorted(CONVERSATIONS_DIR.glob(TOUCH_NOTE_GLOB)):
        text = note_path.read_text()
        fm, _ = split_frontmatter(text)
        if fm.get("type") != "touch":
            continue
        draft = parse_touch_note(note_path)
        if _email_pending(draft) or _linkedin_invite_pending(draft):
            drafts.append(draft)
    return drafts


def count_linkedin_invites_last_n_days(n_days: int = 7) -> tuple[int, list[tuple[str, str]]]:
    """Tally LinkedIn invites sent within the last N days.

    Reads `linkedin_invited_at` from all touch notes.
    Returns (count, list of (person_name, invited_at) for context).
    """
    from datetime import date, timedelta

    cutoff = date.today() - timedelta(days=n_days)
    hits: list[tuple[str, str]] = []
    for note_path in CONVERSATIONS_DIR.glob(TOUCH_NOTE_GLOB):
        text = note_path.read_text()
        fm, _ = split_frontmatter(text)
        if fm.get("type") != "touch":
            continue
        invited_at = fm.get("linkedin_invited_at")
        if not invited_at:
            continue
        try:
            invited_date = invited_at if isinstance(invited_at, date) else date.fromisoformat(str(invited_at))
        except ValueError:
            continue
        if invited_date >= cutoff:
            person = _extract_wikilink_name(fm.get("person")) or "?"
            hits.append((person, str(invited_at)))
    return len(hits), hits


# ----- Surgical frontmatter writeback (preserves formatting, comments, order) -----

def _frontmatter_span(text: str) -> Optional[tuple[int, int]]:
    """Return (start_inclusive, end_exclusive) of the YAML between the --- delimiters."""
    if not text.startswith("---\n"):
        return None
    end = text.find("\n---\n", 4)
    if end == -1:
        return None
    return (4, end + 1)  # include trailing newline of YAML content


def _set_field(fm_text: str, key: str, value) -> str:
    """Set or insert a single frontmatter field, preserving everything else."""
    lines = fm_text.split("\n")
    formatted = _format_yaml_value(value)
    pattern = re.compile(rf"^{re.escape(key)}:\s*(.*?)(\s*#.*)?$")
    for i, line in enumerate(lines):
        m = pattern.match(line)
        if m:
            trailing_comment = m.group(2) or ""
            lines[i] = f"{key}: {formatted}{trailing_comment}"
            return "\n".join(lines)
    # Not found — append at the end (caller handles the trailing newline)
    while lines and lines[-1].strip() == "":
        lines.pop()
    lines.append(f"{key}: {formatted}")
    return "\n".join(lines)


def _format_yaml_value(value) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, date):
        return value.isoformat()
    if value is None:
        return ""
    s = str(value)
    # Quote if contains chars that would confuse YAML
    if any(c in s for c in [":", "#", "[", "]", "{", "}", ","]):
        # Use single quotes, escape any single quotes by doubling
        return "'" + s.replace("'", "''") + "'"
    return s


def update_frontmatter(note_path: Path, updates: dict) -> None:
    """Surgically update specific frontmatter fields. Preserves all other content + formatting."""
    text = note_path.read_text()
    span = _frontmatter_span(text)
    if span is None:
        raise ValueError(f"No frontmatter found in {note_path}")
    start, end = span
    fm_text = text[start:end].rstrip("\n")
    for key, value in updates.items():
        fm_text = _set_field(fm_text, key, value)
    new_text = text[:start] + fm_text + "\n" + text[end:]
    note_path.write_text(new_text)


def tick_outcome_checkbox(note_path: Path, checkbox_label_substring: str) -> bool:
    """Find `- [ ] ...checkbox_label_substring...` and turn it into `- [x] ...`.

    Returns True if a checkbox was ticked, False if none matched.
    """
    text = note_path.read_text()
    pattern = re.compile(
        rf"^(\s*-\s*\[) ( \] [^\n]*{re.escape(checkbox_label_substring)}[^\n]*)$",
        re.MULTILINE | re.IGNORECASE,
    )
    # Simpler approach: line-by-line
    lines = text.split("\n")
    target = checkbox_label_substring.lower()
    changed = False
    for i, line in enumerate(lines):
        if changed:
            break
        stripped = line.lstrip()
        if stripped.startswith("- [ ]") and target in line.lower():
            lines[i] = line.replace("- [ ]", "- [x]", 1)
            changed = True
    if changed:
        note_path.write_text("\n".join(lines))
    return changed
